const INVALID_REQUEST_DATA = "Invalid request data";
const INVALID_REQUEST_DATA_CODE = 400;

const INTERNAL_SERVER_ERROR = "Internal Server error";
const INTERNAL_SERVER_ERROR_CODE = 500;

const INVALID_CREDENTIALS_ERROR =
	"Invalid combination of email and password credentials";
const INVALID_CREDENTIALS_ERROR_CODE = 403;

const UNAUTHENTICATED_ERROR = "Authentication required";
const UNAUTHENTICATED_ERROR_CODE = 401;

const FORBIDDEN_ERROR = "You do not have permission to do that";
const FORBIDDEN_ERROR_CODE = 403;

const INSUFFICIENT_STOCK_ERROR = "Not enough stock available";
const INSUFFICIENT_STOCK_ERROR_CODE = 409;

const EMAIL_DOMAIN_NOT_ALLOWED =
	"Registration is restricted to approved school email domains";
const EMAIL_DOMAIN_NOT_ALLOWED_CODE = 400;

const EMAIL_ALREADY_REGISTERED = "An account with this email already exists";
const EMAIL_ALREADY_REGISTERED_CODE = 409;

const EMAIL_NOT_VERIFIED =
	"Please verify your email before logging in";
const EMAIL_NOT_VERIFIED_CODE = 403;

const INVALID_OR_EXPIRED_CODE = "Invalid or expired verification code";
const INVALID_OR_EXPIRED_CODE_CODE = 400;

module.exports = {
	INVALID_REQUEST_DATA,
	INVALID_REQUEST_DATA_CODE,
	INTERNAL_SERVER_ERROR,
	INTERNAL_SERVER_ERROR_CODE,
	INVALID_CREDENTIALS_ERROR,
	INVALID_CREDENTIALS_ERROR_CODE,
	UNAUTHENTICATED_ERROR,
	UNAUTHENTICATED_ERROR_CODE,
	FORBIDDEN_ERROR,
	FORBIDDEN_ERROR_CODE,
	INSUFFICIENT_STOCK_ERROR,
	INSUFFICIENT_STOCK_ERROR_CODE,
	EMAIL_DOMAIN_NOT_ALLOWED,
	EMAIL_DOMAIN_NOT_ALLOWED_CODE,
	EMAIL_ALREADY_REGISTERED,
	EMAIL_ALREADY_REGISTERED_CODE,
	EMAIL_NOT_VERIFIED,
	EMAIL_NOT_VERIFIED_CODE,
	INVALID_OR_EXPIRED_CODE,
	INVALID_OR_EXPIRED_CODE_CODE,
};
